/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './screens/__root'
import { Route as IndexImport } from './screens/index'
import { Route as TransactionsIndexImport } from './screens/transactions/index'
import { Route as ShowcaseIndexImport } from './screens/showcase/index'
import { Route as CreateTransactionIndexImport } from './screens/create-transaction/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TransactionsIndexRoute = TransactionsIndexImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRoute,
} as any)

const ShowcaseIndexRoute = ShowcaseIndexImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRoute,
} as any)

const CreateTransactionIndexRoute = CreateTransactionIndexImport.update({
  id: '/create-transaction/',
  path: '/create-transaction/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-transaction/': {
      id: '/create-transaction/'
      path: '/create-transaction'
      fullPath: '/create-transaction'
      preLoaderRoute: typeof CreateTransactionIndexImport
      parentRoute: typeof rootRoute
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseIndexImport
      parentRoute: typeof rootRoute
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-transaction': typeof CreateTransactionIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-transaction': typeof CreateTransactionIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-transaction/': typeof CreateTransactionIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-transaction' | '/showcase' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-transaction' | '/showcase' | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/create-transaction/'
    | '/showcase/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTransactionIndexRoute: typeof CreateTransactionIndexRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTransactionIndexRoute: CreateTransactionIndexRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-transaction/",
        "/showcase/",
        "/transactions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-transaction/": {
      "filePath": "create-transaction/index.tsx"
    },
    "/showcase/": {
      "filePath": "showcase/index.tsx"
    },
    "/transactions/": {
      "filePath": "transactions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
