import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home | EasyMilestones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-screen h-screen bg-red-50 antialiased font-medium`}
      >
        {children}
      </body>
    </html>
  );
}
